export const listSkills = [
  { name: "JavaScript", icon: "/icons/js.png" },
  { name: "React", icon: "/icons/react.svg" },
  { name: "Tailwind", icon: "/icons/tailwind.png" },
  { name: "Python", icon: "/icons/phyton.png" },
  { name: "Laravel", icon: "/icons/laravel.png" },
  { name: "MongoDB", icon: "/icons/mongodb.png" },
  { name: "PostgreSQL", icon: "/icons/postgress.png" },
  { name: "PHP", icon: "/icons/php.png" },
  { name: "Flutter", icon: "/icons/flutter.png" },
  { name: "Java", icon: "/icons/java.png" },
  { name: "Ruby", icon: "/icons/ruby.png" },
  { name: "C++", icon: "/icons/c++.png" },
  { name: "Golang", icon: "/icons/golang.png" },
  { name: "Vue", icon: "/icons/vue.png" },
  { name: "Docker", icon: "/icons/docker.png" },
  { name: "Angular", icon: "/icons/angular.png" },
  { name: "TypeScript", icon: "/icons/typescript.png" },
  { name: "Lua", icon: "/icons/lua.png" },
  { name: "Cypress", icon: "/icons/cypress.png" },
  { name: "MySQL", icon: "/icons/mysql.png" },
];
